# Generated by Django 2.0.7 on 2018-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='initial_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
