# Generated by Django 2.0.7 on 2018-07-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180721_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_money',
            field=models.FloatField(default=0),
        ),
    ]
