# Generated by Django 2.0.7 on 2018-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='free_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Trader'), (2, 'Investor')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
