# Generated by Django 2.0.7 on 2018-07-21 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_datebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebalance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
